# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1825, 960)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.base_info = QtWidgets.QTextEdit(self.centralwidget)
        self.base_info.setGeometry(QtCore.QRect(1570, 119, 251, 771))
        self.base_info.setObjectName("base_info")
        self.dislpay_image = QtWidgets.QLabel(self.centralwidget)
        self.dislpay_image.setGeometry(QtCore.QRect(260, 120, 1280, 720))
        self.dislpay_image.setText("")
        self.dislpay_image.setTextFormat(QtCore.Qt.PlainText)
        self.dislpay_image.setPixmap(QtGui.QPixmap("resource/block.png"))
        self.dislpay_image.setObjectName("dislpay_image")
        self.path_list = QtWidgets.QListView(self.centralwidget)
        self.path_list.setGeometry(QtCore.QRect(10, 119, 220, 781))
        self.path_list.setObjectName("path_list")
        self.network_list = QtWidgets.QComboBox(self.centralwidget)
        self.network_list.setGeometry(QtCore.QRect(290, 30, 281, 30))
        self.network_list.setObjectName("network_list")
        self.model_list = QtWidgets.QComboBox(self.centralwidget)
        self.model_list.setGeometry(QtCore.QRect(730, 30, 221, 30))
        self.model_list.setObjectName("model_list")
        self.model_buttom = QtWidgets.QPushButton(self.centralwidget)
        self.model_buttom.setGeometry(QtCore.QRect(970, 30, 120, 30))
        self.model_buttom.setObjectName("model_buttom")
        self.retangle_check = QtWidgets.QRadioButton(self.centralwidget)
        self.retangle_check.setGeometry(QtCore.QRect(1570, 30, 150, 30))
        self.retangle_check.setObjectName("retangle_check")
        self.path_text = QtWidgets.QLineEdit(self.centralwidget)
        self.path_text.setGeometry(QtCore.QRect(1110, 30, 250, 30))
        self.path_text.setObjectName("path_text")
        self.path_buttom = QtWidgets.QPushButton(self.centralwidget)
        self.path_buttom.setGeometry(QtCore.QRect(1380, 30, 111, 30))
        self.path_buttom.setObjectName("path_buttom")
        self.network_buttom = QtWidgets.QPushButton(self.centralwidget)
        self.network_buttom.setGeometry(QtCore.QRect(590, 30, 120, 30))
        self.network_buttom.setObjectName("network_buttom")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1825, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.model_buttom.setText(_translate("MainWindow", "确认模型"))
        self.retangle_check.setText(_translate("MainWindow", "矩形框显示"))
        self.path_buttom.setText(_translate("MainWindow", "选择文件夹"))
        self.network_buttom.setText(_translate("MainWindow", "选择网络"))
